### ISSUE TITLE
Support multiple languages. 

### ISSUE THREAD

**Issue by themasch** [superscriptjs/normalizer#1]
Hi, 

I'm wondering if it would be possible to support multiple languages here (and in the other parts of the bot, like QTypes.) of if this implementation only focuses on american english?

I think supporting various languages would cause a lot of problems (different grammar, different semantic types, translation needed to use ConceptNet...) but would also add a lot of value to the library. There are a lot of people out there who a not native english speakers ;)

**Comment by benhjames** [comment]
Yeah, this would be great but a *lot* of work. It really needs spearheading by someone to get off the ground! Until that day, will close this - cheers. :)
