### ISSUE TITLE
Sequential Regex not getting applied correctly

### ISSUE THREAD

**Issue by vikram-gupta** [superscriptjs/normalizer#4]
Hey,

I wanted to understand the reasoning for which "+" was added between words. The "readme" mentions that it was done so that the "idiom" processor does not remove them. Why do we need this behaviour? It makes the sequential application of regex improper for some cases. Ex. We were excepting to normalize "I don't think so" to "~no" but because of "+", the sentence gets converted to "i do+not think so" and then the idiom processor fails.

How can we solve this?

**Comment by silentrob** [comment]
That may be a bug in this instance. The `+` was inserted to not process that rule anymore (by not matching and subsequent rules)

**Comment by vikram-gupta** [comment]
Thanks ! 
So, we should substitute "don't" with "do not" instead of "do+not".

**Comment by benhjames** [comment]
I think the move to bot-lang in v1.0.0 has made things like this make more sense by using tags instead of explicitly replacing phrases.
